#!/bin/sh
[ -z "$1" ] && echo "file is needed;" && return

READELF=arm-none-linux-gnueabi-readelf
$READELF -v 2>/dev/null || READELF=arm-linux-gnueabihf-readelf

$READELF -a $1 | grep "Shared library:" | cut -f 2 -d '[' | cut -f 1 -d ']'
